# Kuoto Proxy - configuración
server.bind-ip=0.0.0.0
server.port=10305
server.password=123456
server.max-servers=50
server.description=Kuoto Central Server
server.rak-port=19132
server.motd=Kuoto Proxy
server.sub-motd=A Minecraft PE Proxy
server.gamemode=Survival
server.protocol=84
server.version=0.15.10
server.max-players=20

console.enabled=true

logging.level=info
logging.file=kuoto.log
